name: bookishme
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  bloc: ^8.1.4
  locale_names: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0


flutter:

  uses-material-design: true
